spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sample
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      function:
        definition : orderSupplier;paymentEventConsumer # that contains a list of bindable functions. We need to pass the Supplier or Consumer method names divided by a semicolon
      bindings:
        orderSupplier-out-0:
          destination: order-event
        paymentEventConsumer-in-0 :
          destination: payment-event
server:
  port: 8081